"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabaseClient";

export default function HomePage() {
  const [todos, setTodos] = useState<any[]>([]);

  useEffect(() => {
    const fetchTodos = async () => {
      const { data, error } = await supabase.from("todos").select("*");
      if (error) console.error(error);
      else setTodos(data ?? []);
    };

    fetchTodos();
  }, []);

  return (
    <div className="px-4 py-8 sm:py-12 lg:py-16 max-w-7xl mx-auto">
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-emerald-400 to-emerald-600 text-white rounded-lg mb-12 p-8 text-center">
        <h1 className="text-4xl font-bold mb-4">Personalized AI Meal Plans</h1>
        <p className="text-xl mb-6">
          Let our AI do the planning. You focus on cooking and enjoying!
        </p>
        <Link
          href="/sign-up"
          className="inline-block bg-white text-emerald-500 font-medium px-5 py-3 rounded hover:bg-gray-100 transition-colors"
        >
          Get Started
        </Link>
      </section>

      {/* AI-Generated Food Image Section */}
      <section className="mb-12 text-center">
        <h2 className="text-2xl font-semibold mb-4">Today's Food Inspiration 🍽️</h2>
        <p className="text-gray-600 mb-4">
          Here's a delicious dish randomly generated by our AI inspiration engine.
        </p>
        <div className="flex justify-center mb-4">
          <img
            src="https://source.unsplash.com/800x600/?food&sig=123"
            alt="Food test"
            className="rounded-lg shadow-lg max-w-full h-auto"
          />
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="mb-12">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-semibold">How It Works</h2>
          <p className="mt-2 text-gray-600">
            Follow these simple steps to get your personalized meal plan
          </p>
        </div>
        <div className="flex flex-col md:flex-row justify-center items-start space-y-8 md:space-y-0 md:space-x-8">
          {/* Step 1 */}
          <StepCard
            title="Create an Account"
            description="Sign up or sign in to access your personalized meal plans."
            iconPath="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14v7m-3-3h6"
          />
          {/* Step 2 */}
          <StepCard
            title="Set Your Preferences"
            description="Input your dietary preferences and goals to tailor your meal plans."
            iconPath="M9 17v-6a2 2 0 012-2h2a2 2 0 012 2v6 M9 12h6"
          />
          {/* Step 3 */}
          <StepCard
            title="Receive Your Meal Plan"
            description="Get your customized meal plan delivered weekly to your account."
            iconPath="M5 13l4 4L19 7"
          />
        </div>
      </section>

      {/* Your Todos Section */}
      <section className="mt-12">
        <h2 className="text-2xl font-semibold mb-4">Your Todos</h2>
        {todos.length === 0 ? (
          <p className="text-gray-600">No todos yet.</p>
        ) : (
          <ul className="list-disc list-inside">
            {todos.map((todo) => (
              <li key={todo.id} className="mb-1">
                {todo.task} {todo.is_complete ? "(Done)" : ""}
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

// Step Card Component
function StepCard({
  title,
  description,
  iconPath,
}: {
  title: string;
  description: string;
  iconPath: string;
}) {
  return (
    <div className="flex flex-col items-center">
      <div className="bg-emerald-500 text-white rounded-full h-16 w-16 flex items-center justify-center mb-4">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="h-8 w-8"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d={iconPath}
          />
        </svg>
      </div>
      <h3 className="text-xl font-medium mb-2">{title}</h3>
      <p className="text-center text-gray-600">{description}</p>
    </div>
  );
}
